baseURL = 'http://archiko.my.id/'
languageCode = 'id-id'
title = "Archiko"
theme = "wannabe"
paginate = 7
paginatePath = "/"
staticDir = ["static","static/images"]


enableRobotsTXT = true
disableKinds = ["taxonomyTerm"]
[params]
    Description = ""

[taxonomies]
    tag = "tags"

[blackfriday]
  extensions = ["hardLineBreak"]

[markup.goldmark.renderer]
  hardWraps = true
  unsafe = true    

